apiVersion: v1
kind: ConfigMap
data:
  DB_HOST: {{ .Release.Name }}-mongodb-service
  DB_NAME: products_db
  DB_PORT: "{{ .Values.mongodb.port }}"
  PORT: "{{ .Values.products.port }}"
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Name }}
