apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }} 
  type: NodePort    
  ports:
    - protocol: TCP
      port: {{ .Values.products.port }}
      targetPort: {{ .Values.products.port }}
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app: {{ .Release.Name }}-mongodb  
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
